apiVersion: apps/v1                          # API version
kind: Deployment                             # Type of kubernetes resource
metadata:
  name: movie-edge-service-server-deployment # Name of the deployment
  labels:                                    # Labels that will be applied to this deployment
    app: movie-edge-service-server
spec:
  replicas: 1                 # No. of replicas/pods to run in this deployment
  selector:
    matchLabels:              # The deployment applies to any pods mayching the specified labels
      app: movie-edge-service-server
  template:                   # Template for creating the pods in this deployment
    metadata:
      labels:                 # Labels that will be applied to each Pod in this deployment
        app: movie-edge-service-server
    spec:                     # Spec for the containers that will be run in the Pods
      containers:
        - name: movie-edge-service-server
          image: woutervanaelten/edge-service
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8050 # The port that the container exposes
          resources:
            limits:
              cpu: 0.2
              memory: "200Mi"
          env:                    # Environment variables supplied to the Pod
            - name: GENRE_SERVICE_BASEURL
              value: "genre-service-server:8053"
            - name: CAST_SERVICE_BASEURL
              value: "cast-service-server:8052"
            - name: MOVIE_SERVICE_BASEURL
              value: "movie-service-server-server:8051"
---
apiVersion: v1                # API version
kind: Service                 # Type of the kubernetes resource
metadata:
  name: movie-edge-service-server    # Name of the service
  labels:                            # Labels that will be applied to this service
    app: movie-edge-service-server
spec:
  type: NodePort                     # The service will be exposed by opening a Port on each node and proxying it. Allowing connections from outside the cluster
  selector:
    app: movie-edge-service-server   # The service exposes Pods with label `app=movie-edge-service-server`
  ports:                             # Forward incoming connections on port 8080 to the target port 8050
    - name: http
      port: 8050
      targetPort: 8050